### ISSUE TITLE
condition code instead of just textual condition

### ISSUE THREAD

**Issue by rsmith8614** [IOT-DSA/dslink-dart-weather#1]
We are using the "Condition" of the Weather dslink to determine which weather icon to display.  Currently, this is showing the "textual" condition from the Yahoo Weather API, which does not appear to document all possible conditions (at least not where I can find it).  The API does document all possible "condition codes" https://developer.yahoo.com/weather/documentation.html#channel.  Would it be possible to add another node to the weather dslink to include the condition code that we can use to display proper icons?

**Comment by azenla** [comment]
I will add this really soon. I'll close the issue when the update has been pushed out.

Timeframe should be the next 5 hours.

**Comment by kaendfinger** [comment]
I will add this really soon. I'll close the issue when the update has been pushed out.

Timeframe should be the next 5 hours.

**Comment by rsmith8614** [comment]
What is the status of this?  It doesn't appear to have been updated.

**Comment by azenla** [comment]
@rsmith8614 I forgot to commit the update to this. It has been implemented and is now available. Update the DSLink, and re-create your Weather Trackers.

**Comment by kaendfinger** [comment]
@rsmith8614 Hi.
