### ISSUE TITLE
Yahoo! Weather API Retired

### ISSUE THREAD

**Issue by kubeliv** [IOT-DSA/dslink-dart-weather#6]
As of January 3rd, the Yahoo Weather API in its current state has been retired. This means that the link will no longer function. According to this tweet from the Yahoo Developer Network, there is an alternative API that can be accessed that uses OAuth. Here's a link: https://twitter.com/ydn/status/1079784441344446464

**Comment by rinick** [comment]
I built a dslink that use openWeatherMap api : https://github.com/IOT-DSA/dslink-dart-openweathermap
the real time data structure is backward compatible
